# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_main.ipynb.

# %% auto 0
__all__ = ['mySquared', 'foo']

# %% ../nbs/00_main.ipynb 2
def mySquared(x):
    "Returns the square of x"
    return x**2

# %% ../nbs/00_main.ipynb 4
def foo(): pass
